import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ProductProvider from "@/contexts/ProductContext";
import SidebarProvider from "@/contexts/SideBarContext";
import CartProvider from "@/contexts/CartContext";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`inter.className bg-white text-black`}>
      <SidebarProvider>
          <CartProvider>
            <ProductProvider>
              {children}
            </ProductProvider>
          </CartProvider>
        </SidebarProvider>
      </body>
    </html>
  );
}
